name: store_launcher_example
description: Demonstrates how to use the store_launcher plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  store_launcher:
    path: ../

flutter:
  uses-material-design: true
