name: store_launcher
description: A Flutter plugin for launching a Store in the mobile platform. Supports AppStore, PlayStore and AppGallery.
version: 2.0.1
homepage: https://github.com/heqingbao/store_launcher

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.heqingbao.flutter.plugin.store_launcher
    pluginClass: StoreLauncherPlugin
